In [14]:
import numpy as np
import matplotlib.pyplot as plt
a = 2
b = 2
yl = 0
yu = b
xl = 0
xu = a
def f(y):
    return y*((y**2)-(3*a*y)+(2*a**2))
h = 0.5
ny = (yu-yl)/h
nx = (xu-xl)/h
X = [0.5, 1, 1.5]
Y = [0.5, 1, 1.5]
order = int((ny-1)*(nx-1))
A = np.zeros((order, order))
for i in range(int(order/2)):
    for j in range(int(order/2)):
        dif = abs(i-j)
        if(dif==0):
            A[i][j] = 4
            A[i+4][j+4] = 4
        elif(dif==1):
            A[i][j] = -1
            A[i+4][j+4] = -1
        else:
            A[i][j] = 0
            A[i+4][j+4] = 0
for i in range(int(order/2)):
    for j in range(4, 4+int(order/2)):
        dif = abs(4+i-j)
        if(dif==0):
            A[i][j] = -1
            A[i+4][j-4] = -1
        elif(dif==1):
            A[i][j] = 0
            A[i+4][j-4] = 0
        else:
            A[i][j] = 0
            A[i+4][j-4] = 0
B = [0, 0, 0, f(Y[0]), f(Y[1]), f(Y[2])]
print(A, ".Y =", B)
out = np.linalg.inv(A).dot(B)
print("Y =", out)

[[ 4. -1.  0.  0. -1.  0.  0.  0.  0.]
 [-1.  4. -1.  0.  0. -1.  0.  0.  0.]
 [ 0. -1.  4. -1.  0.  0. -1.  0.  0.]
 [ 0.  0. -1.  4.  0.  0.  0. -1.  0.]
 [-1.  0.  0.  0.  4. -1.  0.  0.  0.]
 [ 0. -1.  0.  0. -1.  4. -1.  0.  0.]
 [ 0.  0. -1.  0.  0. -1.  4. -1.  0.]
 [ 0.  0.  0. -1.  0.  0. -1.  4.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]] .Y = [0, 0, 0, 2.625, 3, 1.875]


LinAlgError: Singular matrix