In [3]:
import numpy as np
a=0
b=1
h=0.25
n=int((b-a)/h)
B = np.zeros(n-1)
diag = -2*(1/(h*h))-4
ultri = 1/(h*h)
B = np.array([-15.25, 1.5,-13.75])
A = np.zeros((n-1, n-1))
for i in range(0,n-1):
    for j in range(0,n-1):
        if i-j == 0:
            A[i,j] = diag
        elif i-j == 1 or i-j == -1:
            A[i,j] = ultri
        else:
            A[i,j] = 0
X=np.linalg.inv(A).dot(B)
print(A)
print(X)
print(B)

[[-36.  16.   0.]
 [ 16. -36.  16.]
 [  0.  16. -36.]]
[0.65603741 0.52295918 0.61437075]
[-15.25   1.5  -13.75]
